package com.example.appgasto.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF6C63FF)
val LightOnPrimary = Color.White
val LightPrimaryContainer = Color(0xFFE8E6FF)
val LightOnPrimaryContainer = Color(0xFF1A1450)
val LightSecondary = Color(0xFFFF6584)
val LightOnSecondary = Color.White
val LightSecondaryContainer = Color(0xFFFFE0E6)
val LightOnSecondaryContainer = Color(0xFF3D001A)
val LightTertiary = Color(0xFF00BFA6)
val LightOnTertiary = Color.White
val LightTertiaryContainer = Color(0xFFDFFFF9)
val LightOnTertiaryContainer = Color(0xFF00201B)
val LightSurface = Color(0xFFFEFBFF)
val LightOnSurface = Color(0xFF1B1B1F)
val LightBackground = Color(0xFFF8F7FC)
val LightOnBackground = Color(0xFF1B1B1F)
val LightSurfaceVariant = Color(0xFFF0EEF6)
val LightOnSurfaceVariant = Color(0xFF49454F)
val LightError = Color(0xFFE53935)
val LightOnError = Color.White
val LightOutline = Color(0xFFD0CDD6)

val DarkPrimary = Color(0xFFB4AFFF)
val DarkOnPrimary = Color(0xFF2D2680)
val DarkPrimaryContainer = Color(0xFF433D99)
val DarkOnPrimaryContainer = Color(0xFFE8E6FF)
val DarkSecondary = Color(0xFFFFB2C0)
val DarkOnSecondary = Color(0xFF5E0030)
val DarkSecondaryContainer = Color(0xFF8B1A4A)
val DarkOnSecondaryContainer = Color(0xFFFFE0E6)
val DarkTertiary = Color(0xFF64FFDA)
val DarkOnTertiary = Color(0xFF003D33)
val DarkTertiaryContainer = Color(0xFF005A4D)
val DarkOnTertiaryContainer = Color(0xFFDFFFF9)
val DarkSurface = Color(0xFF1B1B1F)
val DarkOnSurface = Color(0xFFE4E1E6)
val DarkBackground = Color(0xFF131316)
val DarkOnBackground = Color(0xFFE4E1E6)
val DarkSurfaceVariant = Color(0xFF2D2D35)
val DarkOnSurfaceVariant = Color(0xFFCAC4D0)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkOutline = Color(0xFF49454F)

val MatrixPrimary = Color(0xFF00FF41)
val MatrixOnPrimary = Color(0xFF0A0A0A)
val MatrixPrimaryContainer = Color(0xFF003D12)
val MatrixOnPrimaryContainer = Color(0xFF7AFF96)
val MatrixSecondary = Color(0xFF00E676)
val MatrixOnSecondary = Color(0xFF0A0A0A)
val MatrixSecondaryContainer = Color(0xFF004D25)
val MatrixOnSecondaryContainer = Color(0xFFB9FFD4)
val MatrixTertiary = Color(0xFF00FFFF)
val MatrixOnTertiary = Color(0xFF0A0A0A)
val MatrixTertiaryContainer = Color(0xFF003D3D)
val MatrixOnTertiaryContainer = Color(0xFFB9FFFF)
val MatrixSurface = Color(0xFF0A0F0A)
val MatrixOnSurface = Color(0xFF00FF41)
val MatrixBackground = Color(0xFF050A05)
val MatrixOnBackground = Color(0xFF00FF41)
val MatrixSurfaceVariant = Color(0xFF1A2E1A)
val MatrixOnSurfaceVariant = Color(0xFF4CAF50)
val MatrixError = Color(0xFFFF1744)
val MatrixOnError = Color.White
val MatrixOutline = Color(0xFF2E5E2E)

val MatrixGradientStart = Color(0xFF00C853)
val MatrixGradientEnd = Color(0xFF00FF41)
val MatrixGradientTertiary = Color(0xFF00FFFF)

val GradientStart = Color(0xFF6C63FF)
val GradientEnd = Color(0xFFFF6584)
val GradientTertiary = Color(0xFF00BFA6)
